baseurl = "https://silocitylabs.com/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "docs"
title = "SCL Blog"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "sclblog-1"
googleAnalytics = "UA-78226868-1"

[Params]
  subtitle = "Official Blog for Silo City Labs LLC"
  logo = "logo/144x144.png"
  favicon = "favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  gcse = "006156681959470562953:oxkwuulite0"

[[Params.bigimg]]
  src = "img/hexagon.jpg"

[Author]
  name = "Silo City Labs LLC"
  email = "team@silocitylabs.com"
  facebook = "SiloCityLabs"
  gitlab = "silo-city-labs-llc"
  github = "SiloCityLabs/blog"
  twitter = "silocitylabs"
  linkedin-company = "10586208"
  youtube = "channel/UC9vgzat1SRdQ8NNsCQ6d7cA"
  newsletter = "newsletter"

[taxonomies]
  author = "author"
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "cat"
    name = "Categories"
    weight = 2

[[menu.main]]
    parent = "cat"
    name = "Official"
    url = "categories/company/"
    weight = 1

[[menu.main]]
    parent = "cat"
    name = "Side Projects"
    url = "categories/projects/"
    weight = 2

[[menu.main]]
    parent = "cat"
    name = "Deals"
    url = "categories/tech-deals/"
    weight = 3

[[menu.main]]
    parent = "cat"
    name = "Tags"
    url = "tags"
    weight = 4

[[menu.main]]
    name = "Newsletter"
    url = "newsletter"
    weight = 4

