baseurl = "https://silocitylabs.com/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "docs"
title = "SCL Blog"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
googleAds = "ca-pub-6882852717412296"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
  subtitle = "Official Blog for Silo City Labs"
  logo = "logo/144x144.png"
  favicon = "favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  gcse = "006156681959470562953:oxkwuulite0"

[[Params.bigimg]]
  src = "img/sphere.jpg"

[Params.author]
  name = "Silo City Labs"
  email = "team@silocitylabs.com"
  facebook = "SiloCityLabs"
  gitlab = "silo-city-labs-llc"
  github = "SiloCityLabs/blog"
  twitter = "silocitylabs"
  linkedin-company = "10586208"
  youtube = "channel/UC9vgzat1SRdQ8NNsCQ6d7cA"
  newsletter = "newsletter"

[taxonomies]
  author = "author"
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[[menu.main]]
    name = "Shop"
    url = "https://shop.silocitylabs.com"
    weight = 1
    
[[menu.main]]
    name = "Blog"
    url = ""
    weight = 2

[[menu.main]]
    name = "Games"
    url = "https://silocitygames.com"
    weight = 3

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 4

[[menu.main]]
    name = "Newsletter"
    url = "https://shop.silocitylabs.com/pages/subscribe"
    weight = 5

