baseurl = "http://blog2.silocitylabs.com/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "docs"
title = "SCL Blog"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "sclblog-1"
googleAnalytics = "UA-78226868-3"

[Params]
  subtitle = "Official Blog for Silo City Labs LLC"
  logo = "android-chrome-256x256.png"
  favicon = "favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Silo City Labs LLC"
  email = "team@silocitylabs.com"
  facebook = "SiloCityLabs"
  gitlab = "silo-city-labs-llc"
  github = "silocitylabs"
  twitter = "silocitylabs"
  #reddit = "username"
  #linkedin = "company/10586208"
  youtube = "channel/UC9vgzat1SRdQ8NNsCQ6d7cA"

[permalinks]
  posts = "/post/:year/:month/:day/:slug"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "cat"
    name = "Categories"
    weight = 2

[[menu.main]]
    parent = "cat"
    name = "Official"
    url = "tags/official/"
    weight = 1

[[menu.main]]
    parent = "cat"
    name = "Side Projects"
    url = "tags/side-projects/"
    weight = 2

[[menu.main]]
    parent = "cat"
    name = "Deals"
    url = "tags/deals/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
